// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfs4r2dqLnlVgyhs9GJHVwBrUPOsarWVA',
    appId: '1:623858857074:web:ea7c79c0425cba46babeeb',
    messagingSenderId: '623858857074',
    projectId: 'talks-d3253',
    authDomain: 'talks-d3253.firebaseapp.com',
    storageBucket: 'talks-d3253.appspot.com',
    measurementId: 'G-TCR615P7DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDOpnY0saVC5z7uXA-v1O5yKV0fmr8qUQ',
    appId: '1:623858857074:android:7ef96f884a5320dfbabeeb',
    messagingSenderId: '623858857074',
    projectId: 'talks-d3253',
    storageBucket: 'talks-d3253.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj0QfSSfltJSaXsVFPs0dZUfbOziBZCy0',
    appId: '1:623858857074:ios:2f4b0ca8beee3561babeeb',
    messagingSenderId: '623858857074',
    projectId: 'talks-d3253',
    storageBucket: 'talks-d3253.appspot.com',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj0QfSSfltJSaXsVFPs0dZUfbOziBZCy0',
    appId: '1:623858857074:ios:2f4b0ca8beee3561babeeb',
    messagingSenderId: '623858857074',
    projectId: 'talks-d3253',
    storageBucket: 'talks-d3253.appspot.com',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfs4r2dqLnlVgyhs9GJHVwBrUPOsarWVA',
    appId: '1:623858857074:web:5775280ccf95d769babeeb',
    messagingSenderId: '623858857074',
    projectId: 'talks-d3253',
    authDomain: 'talks-d3253.firebaseapp.com',
    storageBucket: 'talks-d3253.appspot.com',
    measurementId: 'G-E4RQ10Y0FE',
  );
}
